// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/name/update/name-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IName, Name } from '../name.model';
import { NameService } from '../service/name.service';
import { Title } from 'app/entities/enumerations/title.model';

@Component({
  selector: 'jhi-name-update',
  templateUrl: './name-update.component.html',
})
export class NameUpdateComponent implements OnInit {
  isSaving = false;
  titleValues = Object.keys(Title);

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required]],
    firstName: [null, [Validators.required]],
    middleName: [],
    lastName: [null, [Validators.required]],
    displayName: [null, [Validators.required]],
  });

  constructor(protected nameService: NameService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ name }) => {
      this.updateForm(name);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const name = this.createFromForm();
    if (name.id !== undefined) {
      this.subscribeToSaveResponse(this.nameService.update(name));
    } else {
      this.subscribeToSaveResponse(this.nameService.create(name));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IName>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe({
      next: () => this.onSaveSuccess(),
      error: () => this.onSaveError(),
    });
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(name: IName): void {
    this.editForm.patchValue({
      id: name.id,
      title: name.title,
      firstName: name.firstName,
      middleName: name.middleName,
      lastName: name.lastName,
      displayName: name.displayName,
    });
  }

  protected createFromForm(): IName {
    return {
      ...new Name(),
      id: this.editForm.get(['id'])!.value,
      title: this.editForm.get(['title'])!.value,
      firstName: this.editForm.get(['firstName'])!.value,
      middleName: this.editForm.get(['middleName'])!.value,
      lastName: this.editForm.get(['lastName'])!.value,
      displayName: this.editForm.get(['displayName'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-name-heading" data-cy="NameCreateUpdateHeading">Create or edit a Name</h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_title">Title</label>
          <select class="form-control" name="title" formControlName="title" id="field_title" data-cy="title">
            <option [ngValue]="null"></option>
            <option *ngFor="let title of titleValues" [value]="title">title</option>
          </select>
          <div *ngIf="editForm.get('title')!.invalid && (editForm.get('title')!.dirty || editForm.get('title')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('title')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_firstName">First Name</label>
          <input type="text" class="form-control" name="firstName" id="field_firstName" data-cy="firstName" formControlName="firstName" />
          <div *ngIf="editForm.get('firstName')!.invalid && (editForm.get('firstName')!.dirty || editForm.get('firstName')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('firstName')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_middleName">Middle Name</label>
          <input
            type="text"
            class="form-control"
            name="middleName"
            id="field_middleName"
            data-cy="middleName"
            formControlName="middleName"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_lastName">Last Name</label>
          <input type="text" class="form-control" name="lastName" id="field_lastName" data-cy="lastName" formControlName="lastName" />
          <div *ngIf="editForm.get('lastName')!.invalid && (editForm.get('lastName')!.dirty || editForm.get('lastName')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('lastName')?.errors?.required"> This field is required. </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" for="field_displayName">Display Name</label>
          <input
            type="text"
            class="form-control"
            name="displayName"
            id="field_displayName"
            data-cy="displayName"
            formControlName="displayName"
          />
          <div *ngIf="editForm.get('displayName')!.invalid && (editForm.get('displayName')!.dirty || editForm.get('displayName')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('displayName')?.errors?.required"> This field is required. </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span>Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span>Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// JavaWeb/property-jhipster/test_name/src/main/webapp/app/entities/name/name-update.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { isNumber, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity, updateEntity, createEntity, reset } from './name.reducer';
import { IName } from 'app/shared/model/name.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';
import { Title } from 'app/shared/model/enumerations/title.model';

export const NameUpdate = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const nameEntity = useAppSelector(state => state.name.entity);
  const loading = useAppSelector(state => state.name.loading);
  const updating = useAppSelector(state => state.name.updating);
  const updateSuccess = useAppSelector(state => state.name.updateSuccess);
  const titleValues = Object.keys(Title);
  const handleClose = () => {
    props.history.push('/name');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(props.match.params.id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    const entity = {
      ...nameEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          title: 'Mr',
          ...nameEntity,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="testNameApp.name.home.createOrEditLabel" data-cy="NameCreateUpdateHeading">
            Create or edit a Name
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? <ValidatedField name="id" required readOnly id="name-id" label="ID" validate={{ required: true }} /> : null}
              <ValidatedField label="Title" id="name-title" name="title" data-cy="title" type="select">
                {titleValues.map(title => (
                  <option value={title} key={title}>
                    {title}
                  </option>
                ))}
              </ValidatedField>
              <ValidatedField
                label="First Name"
                id="name-firstName"
                name="firstName"
                data-cy="firstName"
                type="text"
                validate={{
                  required: { value: true, message: 'This field is required.' },
                }}
              />
              <ValidatedField label="Middle Name" id="name-middleName" name="middleName" data-cy="middleName" type="text" />
              <ValidatedField
                label="Last Name"
                id="name-lastName"
                name="lastName"
                data-cy="lastName"
                type="text"
                validate={{
                  required: { value: true, message: 'This field is required.' },
                }}
              />
              <ValidatedField
                label="Display Name"
                id="name-displayName"
                name="displayName"
                data-cy="displayName"
                type="text"
                validate={{
                  required: { value: true, message: 'This field is required.' },
                }}
              />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/name" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">Back</span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp; Save
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default NameUpdate;
