// JavaWeb/property-jhipster/test_property/src/main/webapp/app/entities/accommodation/accommodation.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './accommodation.reducer';
import { IAccommodation } from 'app/shared/model/accommodation.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Accommodation = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const accommodationList = useAppSelector(state => state.accommodation.entities);
  const loading = useAppSelector(state => state.accommodation.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="accommodation-heading" data-cy="AccommodationHeading">
        <Translate contentKey="testPropertyApp.accommodation.home.title">Accommodations</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="testPropertyApp.accommodation.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="testPropertyApp.accommodation.home.createLabel">Create new Accommodation</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {accommodationList && accommodationList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="testPropertyApp.accommodation.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.accommodation.title">Title</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.accommodation.type">Type</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.accommodation.status">Status</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {accommodationList.map((accommodation, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${accommodation.id}`} color="link" size="sm">
                      {accommodation.id}
                    </Button>
                  </td>
                  <td>{accommodation.title}</td>
                  <td>
                    <Translate contentKey={`testPropertyApp.AccommodationType.${accommodation.type}`} />
                  </td>
                  <td>
                    <Translate contentKey={`testPropertyApp.AccommodationStatus.${accommodation.status}`} />
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${accommodation.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accommodation.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${accommodation.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="testPropertyApp.accommodation.home.notFound">No Accommodations found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Accommodation;

// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/accommodation/list/accommodation.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAccommodation } from '../accommodation.model';
import { AccommodationService } from '../service/accommodation.service';
import { AccommodationDeleteDialogComponent } from '../delete/accommodation-delete-dialog.component';
import { DataUtils } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-accommodation',
  templateUrl: './accommodation.component.html',
})
export class AccommodationComponent implements OnInit {
  accommodations?: IAccommodation[];
  isLoading = false;

  constructor(protected accommodationService: AccommodationService, protected dataUtils: DataUtils, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.accommodationService.query().subscribe({
      next: (res: HttpResponse<IAccommodation[]>) => {
        this.isLoading = false;
        this.accommodations = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IAccommodation): number {
    return item.id!;
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    return this.dataUtils.openFile(base64String, contentType);
  }

  delete(accommodation: IAccommodation): void {
    const modalRef = this.modalService.open(AccommodationDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.accommodation = accommodation;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="AccommodationHeading">
    <span jhiTranslate="testRoomApp.accommodation.home.title">Accommodations</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="testRoomApp.accommodation.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-accommodation"
        [routerLink]="['/accommodation/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="testRoomApp.accommodation.home.createLabel"> Create a new Accommodation </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="accommodations?.length === 0">
    <span jhiTranslate="testRoomApp.accommodation.home.notFound">No accommodations found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="accommodations && accommodations.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.title">Title</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.type">Type</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.status">Status</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.image">Image</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.total">Total</span></th>
          <th scope="col"><span jhiTranslate="testRoomApp.accommodation.property">Property</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let accommodation of accommodations; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/accommodation', accommodation.id, 'view']">{{ accommodation.id }}</a>
          </td>
          <td>{{ accommodation.title }}</td>
          <td jhiTranslate="{{ 'testRoomApp.AccommodationType.' + accommodation.type }}">{{ accommodation.type }}</td>
          <td jhiTranslate="{{ 'testRoomApp.AccommodationStatus.' + accommodation.status }}">{{ accommodation.status }}</td>
          <td>
            <a *ngIf="accommodation.image" (click)="openFile(accommodation.image, accommodation.imageContentType)">
              <img
                [src]="'data:' + accommodation.imageContentType + ';base64,' + accommodation.image"
                style="max-height: 30px"
                alt="accommodation image"
              />
            </a>
            <span *ngIf="accommodation.image">{{ accommodation.imageContentType }}, {{ byteSize(accommodation.image) }}</span>
          </td>
          <td>{{ accommodation.total }}</td>
          <td>
            <div *ngIf="accommodation.property">
              <a [routerLink]="['/property', accommodation.property?.id, 'view']">{{ accommodation.property?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/accommodation', accommodation.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/accommodation', accommodation.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(accommodation)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
