// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/accommodation/list/accommodation.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAccommodation } from '../accommodation.model';
import { AccommodationService } from '../service/accommodation.service';
import { AccommodationDeleteDialogComponent } from '../delete/accommodation-delete-dialog.component';

@Component({
  selector: 'jhi-accommodation',
  templateUrl: './accommodation.component.html',
})
export class AccommodationComponent implements OnInit {
  accommodations?: IAccommodation[];
  isLoading = false;

  constructor(protected accommodationService: AccommodationService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.accommodationService.query().subscribe({
      next: (res: HttpResponse<IAccommodation[]>) => {
        this.isLoading = false;
        this.accommodations = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IAccommodation): number {
    return item.id!;
  }

  delete(accommodation: IAccommodation): void {
    const modalRef = this.modalService.open(AccommodationDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.accommodation = accommodation;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="AccommodationHeading">
    <span>Accommodations</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-accommodation"
        [routerLink]="['/accommodation/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Accommodation </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="accommodations?.length === 0">
    <span>No accommodations found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="accommodations && accommodations.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span>ID</span></th>
          <th scope="col"><span>Title</span></th>
          <th scope="col"><span>Type</span></th>
          <th scope="col"><span>Status</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let accommodation of accommodations; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/accommodation', accommodation.id, 'view']">{{ accommodation.id }}</a>
          </td>
          <td>{{ accommodation.title }}</td>
          <td>{{ accommodation.type }}</td>
          <td>{{ accommodation.status }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/accommodation', accommodation.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/accommodation', accommodation.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(accommodation)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// JavaWeb/property-jhipster/test_accommodation/src/main/webapp/app/entities/accommodation/accommodation.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './accommodation.reducer';
import { IAccommodation } from 'app/shared/model/accommodation.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Accommodation = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const accommodationList = useAppSelector(state => state.accommodation.entities);
  const loading = useAppSelector(state => state.accommodation.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="accommodation-heading" data-cy="AccommodationHeading">
        Accommodations
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} /> Refresh List
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create new Accommodation
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {accommodationList && accommodationList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Type</th>
                <th>Status</th>
                <th>Property</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {accommodationList.map((accommodation, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${accommodation.id}`} color="link" size="sm">
                      {accommodation.id}
                    </Button>
                  </td>
                  <td>{accommodation.title}</td>
                  <td>{accommodation.type}</td>
                  <td>{accommodation.status}</td>
                  <td>
                    {accommodation.property ? <Link to={`property/${accommodation.property.id}`}>{accommodation.property.id}</Link> : ''}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${accommodation.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${accommodation.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${accommodation.id}/delete`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Accommodations found</div>
        )}
      </div>
    </div>
  );
};

export default Accommodation;
