// JavaWeb/property-jhipster/test_property/src/main/webapp/app/entities/property/property-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './property.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const PropertyDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const propertyEntity = useAppSelector(state => state.property.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="propertyDetailsHeading">
          <Translate contentKey="testPropertyApp.property.detail.title">Property</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{propertyEntity.id}</dd>
          <dt>
            <span id="title">
              <Translate contentKey="testPropertyApp.property.title">Title</Translate>
            </span>
          </dt>
          <dd>{propertyEntity.title}</dd>
          <dt>
            <span id="image">
              <Translate contentKey="testPropertyApp.property.image">Image</Translate>
            </span>
          </dt>
          <dd>
            {propertyEntity.image ? (
              <div>
                {propertyEntity.imageContentType ? (
                  <a onClick={openFile(propertyEntity.imageContentType, propertyEntity.image)}>
                    <img src={`data:${propertyEntity.imageContentType};base64,${propertyEntity.image}`} style={{ maxHeight: '30px' }} />
                  </a>
                ) : null}
                <span>
                  {propertyEntity.imageContentType}, {byteSize(propertyEntity.image)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <span id="status">
              <Translate contentKey="testPropertyApp.property.status">Status</Translate>
            </span>
          </dt>
          <dd>{propertyEntity.status}</dd>
          <dt>
            <span id="type">
              <Translate contentKey="testPropertyApp.property.type">Type</Translate>
            </span>
          </dt>
          <dd>{propertyEntity.type}</dd>
          <dt>
            <span id="acreage">
              <Translate contentKey="testPropertyApp.property.acreage">Acreage</Translate>
            </span>
          </dt>
          <dd>{propertyEntity.acreage}</dd>
          <dt>
            <Translate contentKey="testPropertyApp.property.address">Address</Translate>
          </dt>
          <dd>{propertyEntity.address ? propertyEntity.address.street : ''}</dd>
        </dl>
        <Button tag={Link} to="/property" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/property/${propertyEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default PropertyDetail;

// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/property/detail/property-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IProperty } from '../property.model';
import { DataUtils } from 'app/core/util/data-util.service';

@Component({
  selector: 'jhi-property-detail',
  templateUrl: './property-detail.component.html',
})
export class PropertyDetailComponent implements OnInit {
  property: IProperty | null = null;

  constructor(protected dataUtils: DataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ property }) => {
      this.property = property;
    });
  }

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="property">
      <h2 data-cy="propertyDetailsHeading"><span jhiTranslate="testRoomApp.property.detail.title">Property</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ property.id }}</span>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.title">Title</span></dt>
        <dd>
          <span>{{ property.title }}</span>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.type">Type</span></dt>
        <dd>
          <span jhiTranslate="{{ 'testRoomApp.PropertyType.' + property.type }}">{{ property.type }}</span>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.status">Status</span></dt>
        <dd>
          <span jhiTranslate="{{ 'testRoomApp.PropertyStatus.' + property.status }}">{{ property.status }}</span>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.image">Image</span></dt>
        <dd>
          <div *ngIf="property.image">
            <a (click)="openFile(property.image, property.imageContentType)">
              <img [src]="'data:' + property.imageContentType + ';base64,' + property.image" style="max-width: 100%" alt="property image" />
            </a>
            {{ property.imageContentType }}, {{ byteSize(property.image) }}
          </div>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.isUrgent">Is Urgent</span></dt>
        <dd>
          <span>{{ property.isUrgent }}</span>
        </dd>
        <dt><span jhiTranslate="testRoomApp.property.user">User</span></dt>
        <dd>
          <span>{{ property.user?.login }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/property', property.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
