// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/property/list/property.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IProperty } from '../property.model';
import { PropertyService } from '../service/property.service';
import { PropertyDeleteDialogComponent } from '../delete/property-delete-dialog.component';

@Component({
  selector: 'jhi-property',
  templateUrl: './property.component.html',
})
export class PropertyComponent implements OnInit {
  properties?: IProperty[];
  isLoading = false;

  constructor(protected propertyService: PropertyService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.propertyService.query().subscribe({
      next: (res: HttpResponse<IProperty[]>) => {
        this.isLoading = false;
        this.properties = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IProperty): number {
    return item.id!;
  }

  delete(property: IProperty): void {
    const modalRef = this.modalService.open(PropertyDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.property = property;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="PropertyHeading">
    <span>Properties</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-property"
        [routerLink]="['/property/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Property </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="properties?.length === 0">
    <span>No properties found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="properties && properties.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span>ID</span></th>
          <th scope="col"><span>Title</span></th>
          <th scope="col"><span>Type</span></th>
          <th scope="col"><span>Status</span></th>
          <th scope="col"><span>Is Urgent</span></th>
          <th scope="col"><span>Address</span></th>
          <th scope="col"><span>Room</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let property of properties; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/property', property.id, 'view']">{{ property.id }}</a>
          </td>
          <td>{{ property.title }}</td>
          <td>{{ property.type }}</td>
          <td>{{ property.status }}</td>
          <td>{{ property.isUrgent }}</td>
          <td>
            <div *ngIf="property.address">
              <a [routerLink]="['/address', property.address?.id, 'view']">{{ property.address?.street }}</a>
            </div>
          </td>
          <td>
            <span *ngFor="let room of property.rooms; let last = last">
              <a class="form-control-static" [routerLink]="['/room', room.id, 'view']">{{ room.id }}</a
              >{{ last ? '' : ', ' }}
            </span>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/property', property.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/property', property.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(property)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// JavaWeb/property-jhipster/test_name/src/main/webapp/app/entities/property/property.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './property.reducer';
import { IProperty } from 'app/shared/model/property.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Property = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const propertyList = useAppSelector(state => state.property.entities);
  const loading = useAppSelector(state => state.property.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="property-heading" data-cy="PropertyHeading">
        Properties
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} /> Refresh List
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp; Create new Property
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {propertyList && propertyList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>ID</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {propertyList.map((property, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${property.id}`} color="link" size="sm">
                      {property.id}
                    </Button>
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${property.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" /> <span className="d-none d-md-inline">View</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${property.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" /> <span className="d-none d-md-inline">Edit</span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${property.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" /> <span className="d-none d-md-inline">Delete</span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && <div className="alert alert-warning">No Properties found</div>
        )}
      </div>
    </div>
  );
};

export default Property;
