// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/name/list/name.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IName } from '../name.model';
import { NameService } from '../service/name.service';
import { NameDeleteDialogComponent } from '../delete/name-delete-dialog.component';

@Component({
  selector: 'jhi-name',
  templateUrl: './name.component.html',
})
export class NameComponent implements OnInit {
  names?: IName[];
  isLoading = false;

  constructor(protected nameService: NameService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.nameService.query().subscribe({
      next: (res: HttpResponse<IName[]>) => {
        this.isLoading = false;
        this.names = res.body ?? [];
      },
      error: () => {
        this.isLoading = false;
      },
    });
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IName): number {
    return item.id!;
  }

  delete(name: IName): void {
    const modalRef = this.modalService.open(NameDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.name = name;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="NameHeading">
    <span>Names</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span>Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-name"
        [routerLink]="['/name/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span> Create a new Name </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="names?.length === 0">
    <span>No names found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="names && names.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span>ID</span></th>
          <th scope="col"><span>Title</span></th>
          <th scope="col"><span>First Name</span></th>
          <th scope="col"><span>Middle Name</span></th>
          <th scope="col"><span>Last Name</span></th>
          <th scope="col"><span>Display Name</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let name of names; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/name', name.id, 'view']">{{ name.id }}</a>
          </td>
          <td>{{ name.title }}</td>
          <td>{{ name.firstName }}</td>
          <td>{{ name.middleName }}</td>
          <td>{{ name.lastName }}</td>
          <td>{{ name.displayName }}</td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/name', name.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline">View</span>
              </button>

              <button type="submit" [routerLink]="['/name', name.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline">Edit</span>
              </button>

              <button type="submit" (click)="delete(name)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// JavaWeb/property-jhipster/test_property/src/main/webapp/app/entities/name/name.tsx
import React, { useState, useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntities } from './name.reducer';
import { IName } from 'app/shared/model/name.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const Name = (props: RouteComponentProps<{ url: string }>) => {
  const dispatch = useAppDispatch();

  const nameList = useAppSelector(state => state.name.entities);
  const loading = useAppSelector(state => state.name.loading);

  useEffect(() => {
    dispatch(getEntities({}));
  }, []);

  const handleSyncList = () => {
    dispatch(getEntities({}));
  };

  const { match } = props;

  return (
    <div>
      <h2 id="name-heading" data-cy="NameHeading">
        <Translate contentKey="testPropertyApp.name.home.title">Names</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="testPropertyApp.name.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="testPropertyApp.name.home.createLabel">Create new Name</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {nameList && nameList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th>
                  <Translate contentKey="testPropertyApp.name.id">ID</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.name.title">Title</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.name.firstName">First Name</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.name.middleName">Middle Name</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.name.lastName">Last Name</Translate>
                </th>
                <th>
                  <Translate contentKey="testPropertyApp.name.displayName">Display Name</Translate>
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {nameList.map((name, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${name.id}`} color="link" size="sm">
                      {name.id}
                    </Button>
                  </td>
                  <td>
                    <Translate contentKey={`testPropertyApp.Title.${name.title}`} />
                  </td>
                  <td>{name.firstName}</td>
                  <td>{name.middleName}</td>
                  <td>{name.lastName}</td>
                  <td>{name.displayName}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${name.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${name.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${name.id}/delete`} color="danger" size="sm" data-cy="entityDeleteButton">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="testPropertyApp.name.home.notFound">No Names found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default Name;
