// JavaWeb/property-jhipster/test_room/src/main/webapp/app/entities/name/detail/name-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IName } from '../name.model';

@Component({
  selector: 'jhi-name-detail',
  templateUrl: './name-detail.component.html',
})
export class NameDetailComponent implements OnInit {
  name: IName | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ name }) => {
      this.name = name;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="name">
      <h2 data-cy="nameDetailsHeading"><span>Name</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span>ID</span></dt>
        <dd>
          <span>{{ name.id }}</span>
        </dd>
        <dt><span>Title</span></dt>
        <dd>
          <span>{{ name.title }}</span>
        </dd>
        <dt><span>First Name</span></dt>
        <dd>
          <span>{{ name.firstName }}</span>
        </dd>
        <dt><span>Middle Name</span></dt>
        <dd>
          <span>{{ name.middleName }}</span>
        </dd>
        <dt><span>Last Name</span></dt>
        <dd>
          <span>{{ name.lastName }}</span>
        </dd>
        <dt><span>Display Name</span></dt>
        <dd>
          <span>{{ name.displayName }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span>Back</span>
      </button>

      <button type="button" [routerLink]="['/name', name.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span>Edit</span>
      </button>
    </div>
  </div>
</div>

// JavaWeb/property-jhipster/test_property/src/main/webapp/app/entities/name/name-detail.tsx
import React, { useEffect } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { getEntity } from './name.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

export const NameDetail = (props: RouteComponentProps<{ id: string }>) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(getEntity(props.match.params.id));
  }, []);

  const nameEntity = useAppSelector(state => state.name.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="nameDetailsHeading">
          <Translate contentKey="testPropertyApp.name.detail.title">Name</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{nameEntity.id}</dd>
          <dt>
            <span id="title">
              <Translate contentKey="testPropertyApp.name.title">Title</Translate>
            </span>
          </dt>
          <dd>{nameEntity.title}</dd>
          <dt>
            <span id="firstName">
              <Translate contentKey="testPropertyApp.name.firstName">First Name</Translate>
            </span>
          </dt>
          <dd>{nameEntity.firstName}</dd>
          <dt>
            <span id="middleName">
              <Translate contentKey="testPropertyApp.name.middleName">Middle Name</Translate>
            </span>
          </dt>
          <dd>{nameEntity.middleName}</dd>
          <dt>
            <span id="lastName">
              <Translate contentKey="testPropertyApp.name.lastName">Last Name</Translate>
            </span>
          </dt>
          <dd>{nameEntity.lastName}</dd>
          <dt>
            <span id="displayName">
              <Translate contentKey="testPropertyApp.name.displayName">Display Name</Translate>
            </span>
          </dt>
          <dd>{nameEntity.displayName}</dd>
        </dl>
        <Button tag={Link} to="/name" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/name/${nameEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default NameDetail;
